name: テスト実行

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: actions/checkout@v4
    
    - name: Python ${{ matrix.python-version }} のセットアップ
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: 依存パッケージのインストール
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y fsck.ext4 ntfs-3g smartmontools
        
    - name: テストの実行
      run: |
        pytest -v
      env:
        PYTHONPATH: ${{ github.workspace }}
        
    - name: テストカバレッジの計測
      run: |
        pip install pytest-cov
        pytest --cov=src --cov-report=xml
        
    - name: カバレッジレポートのアップロード
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true 